### ISSUE TITLE
GraphView must be used in hardware accelerated mode

### ISSUE THREAD

**Issue by BplAndroid** [appsthatmatter/GraphView#490]
when i try to take a snapshot of my screen in which GraphView has been used, it throws me an error.
"GraphView must be used in hardware accelerated mode"
Even though i make it hardware "acceleration =true" on the required  Activity and even on Application still the problem persists.
I am using version Graphview 4.1.0

**Comment by Robbypatel1357** [comment]
plz any have get the solution?

**Comment by caseymongoven** [comment]
Any ideas for a solution to this? I have tried many different things including the newest version of GraphView 4.2.1. Making the app or activity android:hardwareAccelerated="true" etc.

**Comment by NunoPontes** [comment]
someone using my app had this error (received report on fabric), but I can't reproduce the error, any hints?

**Comment by remotegun** [comment]
I have this problem. It happened for one of our users.
GraphView.java line 292
com.jjoe64.graphview.GraphView.drawGraphElements

**Comment by abh22ishek** [comment]
It looks like there is a bug in Graphview .
I had removed the graphview libraray and implemented with other library and it works fine

**Comment by NunoPontes** [comment]
@abh22ishek can you tell which library you're using right now?

**Comment by abh22ishek** [comment]
i have implemented my own logic , currently i am using canvas with custom view so i have full control over it.
you can give it try to mpchart.

**Comment by RaghuMadivala** [comment]
its due to new chnages not relfcted in threre relesed jar

**Comment by Pimmetje** [comment]
This error happens for me on a android 4.0.4 (emulator). Not on any newer version using the emulator.

**Comment by haiderali1** [comment]
Yes it happens as Pimmetetje said for API15 and not above it and in another thread I saw the illegalArgumentException that is taking place there in drawGraphElements method in GraphView class.
In order to overcome this you can take their code and make that condition to false(take java and res part).
Also It complains regarding not able to find R for which you can have an import statement for original R file
It might not be good for place where its actually required but hope it helps :)

**Comment by appsthatmatter** [comment]
will test it for api 15, android 4.0.4 emulator
